config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: ->(attrs) { attrs['name'].blank? }

  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image

  mount_uploader :main_image, PortfolioUploader
  mount_uploader :thumb_image, PortfolioUploader

  def self.angular
    where(subtitle: 'Angular')
  end

  def self.by_position
    order('position ASC')
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails') }

  after_initialize :set_defaults

  def set_defaults
    # self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    # self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
    # self.main_image  ||= Rails.root.join('public', 'placeholder.png')
    # self.thumb_image ||= Rails.root.join('public', 'placeholder.png')
    main_image
    thumb_image
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: %w[edit update show destroy]
  layout 'portfolio'
  access all: %i[show index angular], user: { except: %i[destroy new create update edit sort] }, site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |_key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    render nothing: true
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def show
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio_item }
      else
        format.html { render :new }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio_item }
      else
        format.html { render :edit }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Porfolio was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(
        :title,
        :subtitle,
        :body,
        :main_image,
        :thumb_image,
        technologies_attributes: [:name]
    )
  end

  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(portfolio_item) do |f| %>
  <div class="row">
    <div class="col-md-6">
      <div class="mb-3">
        <%= f.label :title, class: 'form-label' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="mb-3">
        <%= f.label :subtitle, class: 'form-label' %>
        <%= f.text_field :subtitle, class: 'form-control' %>
      </div>
      <div class="mb-3">
        <label class="btn btn-primary">
          Upload a main image file <%= f.file_field :main_image, style: 'display: none;' %>
        </label>
      </div>
      <div class="mb-3">
      <label class="btn btn-primary">
          Upload a thumb image file <%= f.file_field :thumb_image, style: 'display: none;' %>
        </label>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <%= f.label :body, class: 'form-label' %>
        <%= f.text_area :body, class: 'form-control', rows: '15' %>
      </div>
    </div>
  </div>
  <hr>
  <div class="col-md-12">
    <h2>Technologies used:</h2>
    <div>
      <%= f.fields_for :technologies do |technology_f| %>
        <div class="mb-3">
          <%= technology_f.label :name, class: 'form-label' %>
          <%= technology_f.text_field :name, class: 'form-control' %>
        </div>
      <% end %>
    </div>
    <div class="d-grid">
      <%= f.submit 'Save Portfolio Item', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col">
    <div class="card shadow-sm" data-id="<%= portfolio_item.id %>">
        <%= image_tag portfolio_item.thumb_image.url unless portfolio_item.thumb_image.nil? %>
        <div class="card-body">
            <p class="card-text">
                <span>
                    <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %>
                    <%= portfolio_item.subtitle %>
                </span>
            </p>
        </div>
    </div>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_url if logged_in?(:site_admin) %>

<% @angular_portfolio_items.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
  <%= link_to 'Delete Portfolio Item',
              portfolio_path(portfolio_item),
              method: :delete,
              data: {confirm: 'Are you sure?'} if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
<h1>Edit this portfolio item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 <%= "sortable" if logged_in?(:site_admin)%> ">
    <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
  <h1>Create a new portfolio item</h1>

  <%= render 'form', portfolio_item: @portfolio_item if logged_in?(:site_admin) %>
</div>

app/views/portfolios/show.html.erb
<div class="container d-flex portfolio-container">
  <div class="col justify-content-center">
    <div class="row">
      <div class="col-md-7 col-sm-7">
        <%= image_tag @portfolio_item.main_image.to_s, class: "img-fluid", width: "100%" %>
      </div>
      <div class="col-md-5 col-sm-5">
        <h1><%= @portfolio_item.title %></h1>
        <hr>
        <em><%= @portfolio_item.subtitle %></em>
        <p><%= @portfolio_item.body %></p>
        <hr>
        <h3>Technologies Used</h3>
        <% @portfolio_item.technologies.each do |t| %>
          <p><%= t.name %></p>
        <% end %>
      </div>
    </div>
    <div class="row mt-4">
      <%= link_to "View All Portfolio Items", portfolios_path, class: "text-center" %>
    </div>
  </div>
</div>